version: "3.7"

services:
  app:
    image: castopod/app:latest
    volumes:
      - ./castopod-media:/opt/castopod/public/media
    environment:
      MYSQL_DATABASE: castopod
      MYSQL_USER: castopod
      MYSQL_PASSWORD: changeme
      CP_BASEURL: "https://${BASE_URL}"
      CP_ANALYTICS_SALT: changeme
      CP_CACHE_HANDLER: redis
      CP_REDIS_HOST: redis
      CP_EMAIL_SMTP_HOST: ${EMAIL_HOST}
      CP_EMAIL_FROM: ${EMAIL_FROM_ADDRESS}
      CP_EMAIL_SMTP_USERNAME:	${EMAIL_USER}
      CP_EMAIL_SMTP_PASSWORD: ${EMAIL_PASSWORD}
      CP_EMAIL_SMTP_PORT: ${EMAIL_PORT}
    restart: always

  web-server:
    image: castopod/web-server:latest
    volumes:
      - ./castopod-media:/var/www/html/media
    ports:
      - 172.17.0.1:8989:80
    restart: always

  mariadb:
    image: mariadb:10.5
    volumes:
      - ./castopod-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: castopod
      MYSQL_USER: castopod
      MYSQL_PASSWORD: changeme
    restart: always

  redis:
    image: redis:7.0-alpine
    volumes:
      - ./castopod-cache:/data

  # this container is optional
  # add this if you want to use the videoclips feature
  # ffmpeg:
  #   image: castopod/video-clipper:latest
  #   volumes:
  #     - ./castopod-media:/opt/castopod/public/media
  #   environment:
  #     MYSQL_DATABASE: castopod
  #     MYSQL_USER: castopod
  #     MYSQL_PASSWORD: changeme
  #   restart: always